name: walker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5
  google_fonts: ^6.1.0
  cube_transition_plus: ^2.0.1
  widget_mask: ^1.0.0+0
  iconsax: ^0.0.8
  image_sequence_animator: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
     - assets/location.png
     - assets/mask.png
     - assets/pizza.png
     - assets/road_from_drone.png
     - assets/temp.png
     - assets/icons/analytics.svg
     - assets/icons/clock.svg
     - assets/icons/fire.svg
     - assets/icons/light.svg
     - assets/icons/menu.svg
     - assets/icons/moon.svg
     - assets/icons/profile.svg
     - assets/icons/steps.svg
     - assets/icons/walking.svg
     - assets/walking-animation/frame_0000.png
     - assets/walking-animation/frame_0001.png
     - assets/walking-animation/frame_0002.png
     - assets/walking-animation/frame_0003.png
     - assets/walking-animation/frame_0004.png
     - assets/walking-animation/frame_0005.png
     - assets/walking-animation/frame_0006.png
     - assets/walking-animation/frame_0007.png
     - assets/walking-animation/frame_0008.png
     - assets/walking-animation/frame_0009.png
     - assets/walking-animation/frame_0010.png
     - assets/walking-animation/frame_0011.png
     - assets/walking-animation/frame_0012.png
     - assets/walking-animation/frame_0013.png
     - assets/walking-animation/frame_0014.png
     - assets/walking-animation/frame_0015.png
     - assets/walking-animation/frame_0016.png
     - assets/walking-animation/frame_0017.png
     - assets/walking-animation/frame_0018.png
     - assets/walking-animation/frame_0019.png
     - assets/walking-animation/frame_0020.png
     - assets/walking-animation/frame_0021.png
     - assets/walking-animation/frame_0022.png
     - assets/walking-animation/frame_0023.png
     - assets/walking-animation/frame_0024.png
     - assets/walking-animation/frame_0025.png
     - assets/walking-animation/frame_0026.png
     - assets/walking-animation/frame_0027.png
     - assets/walking-animation/frame_0028.png
     - assets/walking-animation/frame_0029.png
     - assets/walking-animation/frame_0030.png
     - assets/walking-animation/frame_0031.png
     - assets/walking-animation/frame_0032.png
     - assets/walking-animation/frame_0033.png
     - assets/walking-animation/frame_0034.png
     - assets/walking-animation/frame_0035.png
     - assets/walking-animation/frame_0036.png
     - assets/walking-animation/frame_0037.png
     - assets/walking-animation/frame_0038.png



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
